/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Comment blocks",
  "description": "Add comment blocks to the editor.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
  ],
  "enabledByDefault": false
};
export default manifest;
