name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install
      run: |
        npm install --save scratch-blocks
        npm install
    - run: npm ci
    - run: npm run build
    - run: npm run test:unit
    - name: compress
      run: |
        chmod 777 ./Compress.sh
        ./Compress.sh
    - run: cp url.html build/url.html    
    - name: Download artifact
      uses: aochmann/actions-download-artifact@1.0.0
      with:
        # Optional, GitHub token
        github_token: ${{secrets.GITHUB_TOKEN}}

        name: pointerlock

        # Optional, download latest artifact
        latest: true

        # Optional, directory where to extract artifact
        path: t
    - run: |
        tar -xvf t/pointerlock.tar build
        date > build/build-date.html
        echo -e '\n' >> build/build-date.html
        ls -alR >> build/build-date.html
    - name: script
      run: |
        echo -e '\ns=document.createElement("script");s.src="https://lll69.github.io/tools/track.js";s.setAttribute("defer","");s.setAttribute("async","");document.head.appendChild(s);' >> build/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.js
        echo -e '\ns=document.createElement("script");s.src="https://lll69.github.io/tools/track.js";s.setAttribute("defer","");s.setAttribute("async","");document.head.appendChild(s);' >> build/pointerlock/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.js
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: build
        verbose: true
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
