name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run build
    - run: npm run test:unit
    - run: tar -cvf build.tar build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: build.tar
    
