name: Node.js CI

on:
  push:
    branches: [ pointerlock ]
  pull_request:
    branches: [ pointerlock ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: |
        npm install --save scratch-blocks
        npm install
    - run: npm run build
    - run: npm run test:unit
    - run: |
        mv build pointerlock
        tar -cvf pointerlock.tar pointerlock
        mv pointerlock build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        name: pointerlock
        path: pointerlock.tar
