name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build
    - run: npm run test:unit
    - name: compress
      run: |
        chmod 777 ./Compress.sh
        ./Compress.sh
    - run: date > build/build-date.html
    - run: echo -e '\ns=document.createElement("script");s.src="https://lll69.github.io/tools/track.js";s.setAttribute("defer","");s.setAttribute("async","");document.head.appendChild(s);' >> build/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.js
    - run: cp url.html build/url.html
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: build
        verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
