name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install
      run: |
        rm package-lock.json
        npm install --save scratch-blocks scratch-parser
        npm install
    - run: |
        rm -r node_modules/scratch-vm/node_modules/scratch-parser
        mv node_modules/scratch-parser node_modules/scratch-vm/node_modules/scratch-parser
    - run: npm run build
    #- run: npm run test:unit
    #- run: |
    #    cp url.html build/url.html
    #    cp 404.html build/404.html
    - name: Download artifact
      uses: bettermarks/action-artifact-download@0.3.0
      with:
        # Optional, GitHub token
        repo: lll69/turbo-warp-scratch-gui
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: pointerlock
        rename: pointerlock.zip
    - run: |
        unzip pointerlock
        tar -xvf pointerlock.tar -C build
    #- name: compress
    #  run: |
    #    chmod 777 ./Compress.sh
    #    ./Compress.sh
    #- name: script
    #  run: |
    #    echo -e '\ns=document.createElement("script");s.src="https://lll69.github.io/tools/track.js";s.setAttribute("defer","");s.setAttribute("async","");document.head.appendChild(s);' >> build/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.js
    #    echo -e '\ns=document.createElement("script");s.src="https://lll69.github.io/tools/track.js";s.setAttribute("defer","");s.setAttribute("async","");document.head.appendChild(s);' >> build/pointerlock/js/vendors~addon-settings~credits~editor~embed~fullscreen~player.js
    - name: GitHub Pages
      uses: lll69/ghpages@v2.6.0
      with:
        build_dir: build
        target_branch: gh-page
        verbose: true
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
